# Generated by Django 4.2.1 on 2023-06-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='number_store',
            name='team1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='number_store',
            name='team2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='number_store',
            name='winner',
            field=models.CharField(default='', max_length=50),
        ),
    ]
